config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks'}
  resources :states, only: [:index, :show]
  resources :parks
  resources :parks, only: [:show] do
    resources :reviews
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'states#index'

end

app/models/activity.rb
class Activity < ApplicationRecord
    has_many :reviews
    has_many :parks, through: :reviews

    validates_presence_of :name
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
    has_many :parks
    has_many :activities

    validates_presence_of :name, :zipcode, :state
end

app/models/park.rb
class Park < ApplicationRecord
    has_many :reviews
    has_many :activities, through: :reviews
    belongs_to :city
    belongs_to :state

    validates :name, presence: true, uniqueness: true

    def accessible_reviews(accessible)
        park_reviews = self.reviews.select_by_accessibility(accessible)
    end
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :user
    belongs_to :activity
    belongs_to :park

    validates :review, :rating, :title, presence: true
    validates :rating, inclusion: { in: 1..5 }
    validates :user_id, uniqueness: {scope: :park_id, 
        message: "can only review a park once" }, on: :create
    scope :select_by_accessibility, -> (selection) { where("accessible = ?", selection) }

    def display_accessibility(user, activity, park)
        if self.accessible == "true"
            "#{user.make_name} Found #{activity.name} at #{park.name} To Be Accessible"
        else
            "#{user.make_name} Found #{activity.name} at #{park.name} To Not Be Accessible"
        end
    end

    def stars
        if self.rating == 1
            "#{self.rating} Star"
        else
            "#{self.rating} Stars"
        end
    end
end

app/models/state.rb
class State < ApplicationRecord
    has_many :cities
    has_many :parks, through: :cities

    validates_presence_of :name, :abbreviation
    validates :abbreviation, length: { is: 2 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :parks
  has_many :activities
  has_many :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[google_oauth2]

  def make_name
    self.email.split("@")[0].capitalize
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      #user.name = auth.info.name   # assuming the user model has a name
      #user.image = auth.info.image # assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails, 
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end


  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/parks_controller.rb
class ParksController < ApplicationController
    
    def new
        @park = Park.new
        @state = cookies[:state_id]
    end

    def create
        @park = Park.create(parks_params)
        if @park.save
            redirect_to park_path(@park)
        else
            @state = cookies[:state_id]
            render :new
        end
    end

    def show
        @park = Park.find_by_id(params[:id])
        if !params[:accessible].blank?
            @park_reviews = @park.accessible_reviews(params[:accessible])
                if @park_reviews.empty?
                    flash.now[:alert] = "Could not find any reviews matching your search criteria"
                end 
        else
            @park_reviews = @park.reviews
        end
    end

    def edit
        @park = Park.find(params[:id])
    end

    def update
        @park = Park.find(params[:id])
        @state = cookies[:state_id]
        @park.update(parks_params)
        redirect_to park_path(@park)
    end

    def destroy
        @park = Park.find(params[:id]).destroy
        redirect_to root_path, notice: "Successfully deleted."
    end


    private

    def parks_params
        params.require(:park).permit(:name, :state_id, :city_id, :user_id, :accessible, :rating, :park_reviews)
    end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

    def new
        @park = Park.find_by_id(params[:park_id])
        @review = Review.new(park_id: @park.id)
    end

    def create
        @review = Review.create(reviews_params)
        @park = Park.find_by_id(params[:park_id])
        if @review.save
            redirect_to park_review_path(@park, @review)
        else
            render partial: 'reviews/form'
        end
    end

    def show
        @review = Review.find_by_id(params[:id])
        @user = User.find_by_id(@review.user_id)
        @activity = Activity.find_by_id(@review.activity_id)
        @park = Park.find_by_id(params[:park_id])
    end

    def edit
        @park = Park.find(params[:park_id])
        @review = Review.find(params[:id])
    end

    def update
        @review = Review.find(params[:id])
        @park = Park.find(params[:park_id])
        @review.update(reviews_params)
        redirect_to park_review_path(@park, @review)
    end

    def destroy
        @review = Review.find(params[:id]).destroy
        redirect_to root_path, notice: "Successfully deleted."
    end


    private

    def reviews_params
        params.require(:review).permit(:review, :park_id, :activity_id, :user_id, :accessible, :title, :rating)
    end
end

app/controllers/states_controller.rb
class StatesController < ApplicationController
    def index
      @states = State.all
    end

    def show
      cookies.delete :state
      @state = State.find(params[:id])
      cookies[:state_id] = @state.id
    end
    
  end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
    skip_before_action :verify_authenticity_token, only: :google_oauth2

    def google_oauth2
      # You need to implement the method below in your model (e.g. app/models/user.rb)
      @user = User.from_omniauth(request.env["omniauth.auth"])
      if @user.persisted?
        sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
        set_flash_message(:notice, :success, kind: "Google") if is_navigational_format?
      else
        session["devise.google_oauth2_data"] = request.env["omniauth.auth"]
        redirect_to new_user_registration_url
      end
    end
  
    def failure
      redirect_to root_path
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/parks_helper.rb
module ParksHelper

    def park_author(park)
        current_user.id == park.user_id
    end

end

app/helpers/reviews_helper.rb
module ReviewsHelper

    def review_author(review)
        user_signed_in? && current_user.id == review.user_id
    end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsAccessibilityApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/parks/_error.html.erb
<% if @park.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@park.errors.count, "error") %>
        prohibited this from being saved: </h2>

      <ul><% @park.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

app/views/parks/_form.html.erb
<%= form_for @park do |f| %>
  <%= render "error" %>
  <strong><%= f.label "Park Name" %><br></strong>
  <%= f.text_field :name %><br><br>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.hidden_field :state_id, value: @state %>
  <strong><%= f.label "Select City" %></strong><br>
  <%= f.collection_select :city_id, City.where(state_id: @state), :id, :name %><br><br>
  <%= f.submit %>

<% end %>

app/views/parks/edit.html.erb
<%= render 'form' %>

app/views/parks/new.html.erb
<h1>Create New Park for <%= "#{State.find_by_id(@state).name}" if @state %></h1>
<body>
    <%= render 'form' %>
</body>

<footer>
    <%= link_to "Go Home", root_path %>
</footer>

app/views/parks/show.html.erb
<header><h1><%= @park.name %></h1>
<h2><%= @park.city.name%> - <%= @park.state.name%></h2></header>

    <body>


    <h4>Filter Park Reviews by Accessibility :</h4>
    <%= form_tag("/parks/#{@park.id}", method: "get") do %>
        <%= select_tag "accessible", options_for_select( { "Accessible" => true, "Not Accessible" => false, " " => " "}) %>

        <%= submit_tag "Filter Reviews" %>
    <% end %>

    <p>
        <% @park_reviews.each do |review| %>
            <%= link_to "#{review.title} - #{review.rating} stars", park_review_path(@park, review) %><br>            
        <% end %>
    </p>


    <p>
        <% if user_signed_in? %>
            <p><%= link_to "Add Review for #{@park.name}", new_park_review_path(@park, @review) %></p><br>
        <% end %>
          
        <% if user_signed_in? && park_author(@park) %>
            <%= link_to "Edit #{@park.name}", edit_park_path(@park) %>
            <%= button_to "Delete #{@park.name}", park_path(@park), method: :delete %>
        <% end %>
    </p>

</body>

<footer>
    <%= link_to "View Other Parks in #{@park.state.name}", state_path(@park.state_id)%>
    <%= link_to "Home", root_path %>
</footer>

app/views/reviews/_error.html.erb
<% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %>
        prohibited this from being saved: </h2>

      <ul><% @review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

app/views/reviews/_form.html.erb
<%= form_for([@park, @review]) do |f| %>
  <%= render "error" %>
  
  <%= f.label :title %><br>
  <%= f.text_field :title%><br>

  <strong><%= f.label "Select Activity" %><br></strong><br>
  <%= f.collection_select :activity_id, Activity.all, :id, :name, required: true %><br><br>
  <strong><%= f.label :accessible, "Is this activity accessible?" %></strong><br>
  <%= f.select :accessible, [["Yes", true], ["No", false]] %><br><br>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.hidden_field :park_id %>

  <strong><%= f.label :rating %><br></strong>
  <%= f.number_field :rating, in: 1..5 %><br><br>

  <strong><%= f.label :review %></strong><br>
  <%= f.text_area :review %><br><br>
  
  <%= f.submit %>
<% end %>

app/views/reviews/edit.html.erb
<h1>Edit Your Review: </h1>
<body><%= render "form" %></body>

app/views/reviews/new.html.erb
<h1>Create New Review for <%= @park.name %>: </h1>
<body><%= render 'form' %></body>

app/views/reviews/show.html.erb
<h1><%= @review.title %></h1>
<h4><%= @review.display_accessibility(@user, @activity, @park) %> </h4>

<h5><%= @review.stars %></h5>
<p><%= @review.review %></p>

<%  if user_signed_in? && !review_author(@review) %>
    <%= link_to "Leave a Review For #{@park.name}", new_park_review_path(@park, @review) %><br>
<% elsif review_author(@review) %>
    <%= link_to "Edit Your Review", edit_park_review_path(@park, @review) %><br>
    <%= button_to "Delete Your Review", park_review_path(@park, @review), method: :delete %>
<% end %>
<br>


<footer><%= link_to "Go Back To #{@park.name}", park_path(@park) %><br>
<%= link_to "View Other Parks in #{@park.state.name}", state_path(@park.state) %><br>
<%= link_to "Home", root_path %><br>
<%= render "users/links" %><br></footer>

app/views/states/index.html.erb
<%= render 'users/links' %>

<% @states.each do |state|%>
    <%= link_to state.name, state_path(state) %><br>
<% end %>

app/views/states/show.html.erb
<header> <%= render 'users/links' %> </header>
<h1><%= @state.name %>'s Parks</h1>
<h3><%= @state.parks.count %> Parks Found </h3>


<ul>
    <% @state.parks.each do |park| %>
        <li><strong><%= link_to "#{park.name}", park_path(park) %></strong></li>
    <% end %>
</ul>

<% if user_signed_in? %>
    <%= link_to "Create New Park for #{@state.name}", new_park_path %>
<% end %>

<%= link_to "Go Home", root_path %>

app/views/users/_links.html.erb
    <% if current_user %>
        <%= button_to "Sign Out", destroy_user_session_path, method: :delete %>
    <% else %>
        <%= link_to "Sign Up", new_user_registration_path %><br>
        <%= link_to "Sign In", new_user_session_path %><br>
        <%= button_to "Sign in with Google", user_google_oauth2_omniauth_authorize_path %><br><br>
    <% end %>
</header>